---
abstract: 'Output XML described by a Perl data structure'
author:
  - 'Nic Wolff <nic@angel.net>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.39
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-FromArrayref
provides:
  XML::FromArrayref:
    file: lib/XML/FromArrayref.pm
    version: 1.01
requires:
  HTML::Entities: 0
  URI::Escape: 0
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
